### ISSUE TITLE
class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')

### ISSUE THREAD

**Issue by jojeda-four-id** [luisamesty/Amerpsoft-iDempiere-community#1]
Hola buenas tardes amigo, Estoy haciendo uso de tu plugins **org.amerpsoft.com.idempiere.editors-com** en la versión 10 de iDempiere y al momento de abrir la ventana de tercero e intentar abril la pestaña de localización me da el siguiente error:  

he tratado de resolverlo pero no he podido.

```
19:00:18.438===========> UiEngineImpl.error:  [900]
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')
	at org.compiere.model.GridTab.loadDependentInfo(GridTab.java:2104)
	at org.compiere.model.GridTab.setCurrentRow(GridTab.java:2629)
	at org.compiere.model.GridTab.dataIgnore(GridTab.java:1146)
	at org.adempiere.webui.adwindow.CompositeADTabbox.dataIgnore(CompositeADTabbox.java:1014)
	at org.adempiere.webui.adwindow.AbstractADWindowContent.saveAndNavigate(AbstractADWindowContent.java:1572)
	at org.adempiere.webui.adwindow.CompositeADTabbox$1.onEvent(CompositeADTabbox.java:133)
	at org.adempiere.webui.adwindow.DetailPane.onEdit(DetailPane.java:1000)
	at org.adempiere.webui.adwindow.DetailPane$2.onEvent(DetailPane.java:333)
	at org.zkoss.zk.ui.AbstractComponent.onEvent(AbstractComponent.java:3191)
	at org.zkoss.zk.ui.AbstractComponent.service(AbstractComponent.java:3161)
	at org.zkoss.zk.ui.AbstractComponent.service(AbstractComponent.java:3103)
	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:138)
	at org.zkoss.zk.ui.impl.UiEngineImpl.processEvent(UiEngineImpl.java:1884)
	at org.zkoss.zk.ui.impl.UiEngineImpl.process(UiEngineImpl.java:1656)
	at org.zkoss.zk.ui.impl.UiEngineImpl.execUpdate(UiEngineImpl.java:1323)
	at org.zkoss.zk.au.http.DHtmlUpdateServlet.process(DHtmlUpdateServlet.java:571)
	at org.zkoss.zk.au.http.DHtmlUpdateServlet.doGet(DHtmlUpdateServlet.java:451)
	at org.zkoss.zk.au.http.DHtmlUpdateServlet.doPost(DHtmlUpdateServlet.java:459)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:523)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1410)
```

![Captura de pantalla de 2023-02-23 19-03-44](https://user-images.githubusercontent.com/67495969/221051239-c63832e8-786f-4736-8a74-1bca971545ca.png)

**Comment by luisamesty** [comment]
Actualiza a Idempiere 11
